import React from "react";

function PlantSearchPage(setSearch, search) {
  //Plant data
  const plantList = {
    wildstrawberry: {
      name: "Wild Strawberry",
      bloomTime: "Spring",
      color: "White",
      height: "Ground cover",
      sun: "Full sun",
      soiltype: "Wet",
    },
    goldenalexanders: {
      name: "Golden Alexanders",
      bloomTime: "Spring",
      color: "Yellow",
      height: "Short",
      sun: "Full sun",
      soiltype: "Wet",
    },
    bluewildindigo: {
      name: "Blue Wild Indigo",
      bloomTime: "Spring",
      color: "Blue",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    earlysunflower: {
      name: "Early Sunflower",
      bloomTime: "Summer",
      color: "Yellow",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    swampmilkweed: {
      name: "Swamp Milkweed",
      bloomTime: "Summer",
      color: "Pink",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    purpleconeflowers: {
      name: "Purple Coneflower",
      bloomTime: "Summer",
      color: "Purple",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    wildbergamot: {
      name: "Wild Bergamot",
      bloomTime: "Summer",
      color: "Pink",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    bluevervain: {
      name: "Blue Vervain",
      bloomTime: "Common Ironweed",
      color: "Purple",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    commonironweed: {
      name: "Common Ironweed",
      bloomTime: "Summer",
      color: "Purple",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    prairieblazingstar: {
      name: "Prairie Blazing Star",
      bloomTime: "Summer",
      color: "Purple",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    rosemallow: {
      name: "Rose Mallow",
      bloomTime: "Summer",
      color: "White",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    cardinalflower: {
      name: "Cardinal Flower",
      bloomTime: "Summer",
      color: "Red",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    joepyeweed: {
      name: "Joe Pye Weed",
      bloomTime: "Summer",
      color: "Pink",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    stiffgoldenrod: {
      name: "Stiff Goldenrod",
      bloomTime: "Fall",
      color: "Yellow",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    sneezeweed: {
      name: "Sneezeweed",
      bloomTime: "Fall",
      color: "Yellow",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
    newenglandaster: {
      name: "New England Aster",
      bloomTime: "Fall",
      color: "Purple",
      height: "Medium",
      sun: "Full sun",
      soiltype: "Wet",
    },
  };
}
